### ISSUE TITLE
Support for multiple languages in a single Markdown file

### ISSUE THREAD

**Issue by syroezhkin** [mlange-42/yarner#181]
To use multiple languages in a single Markdown file, It would be useful to move `block_name_prefix`, `macro_start` and etc.  from `[parsr]` section in `Yarner.toml` file to language specific settings.

[parser]
~~block_name_prefix = "//-"~~
~~macro_start = "//>"~~
~~macro_end = "."~~
...

Rust example:
```toml
[language.rs]
block_name_prefix = "//-"
macro_start = "// ==>"
macro_end = "."
```

Python example:
```toml
[language.py]
block_name_prefix = "#-"
macro_start = "# ==>"
macro_end = "."
```

This way we will be able to use multiple languages with different comment tags in one Markdown file:

~~~markdown

## Rust code example

```rust
//- file:example.rs
println!("Have fun with Yarner!");
```

## Python code example

```python
#- file:example.py
print("Have fun with Yarner!")
```

~~~

Now the highlighting of the comment code in the text editor will work correctly.

**Comment by mlange-42** [comment]
Thanks @syroezhkin for this suggestion! Will see if I can find the time to implement it.

**Comment by mlange-42** [comment]
As a note: nothing currently presents authors from using multiple languages in a single Markdown file (or Yarner project). The undifferentiated block and makro markers may just screw up syntax highlighting for those lines.

**Comment by tp86** [comment]
Alternatively, these settings could also just accept (optionally) multiple values instead of per-language values. You could then choose appropriate value for file type.

Example above would be then
```toml
[parser]
block_name_prefix = ["//-", "#-"]
macro_start = ["// ==>", "# ==>"]
macro_end = "."
```
