### ISSUE TITLE
[Documentation] Document language-specific settings (block labels, eof, ...)

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/yarner#24]
* [x] ~~Documents in Features.md~~ document with reverse mode
* [x] Add examples to generated Yarner.toml templates

Rust example:

```toml
[language.rs]
comment_start = "//"
block_start = "<@"
block_end = "@>"
clear_blank_lines = true
eof_newline = true
```
